# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#

board: [ "nice_nano_v2","mikoto"]
shield: [ "charybdis_left","charybdis_right","sofle-plus_left lpm_view_adapter lpm_view","sofle-plus_right lpm_view_adapter lpm_view"]

snippet: ["studio-rpc-usb-uart"]

include:
  - board: corne-v4_left
    snippet: studio-rpc-usb-uart
  - board: corne-v4_right
    snippet: studio-rpc-usb-uart
